/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/approve-main` | `/approve-main`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/hr-main` | `/hr-main`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more-main` | `/more-main`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/resource-main` | `/resource-main`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/approve/[category]` | `/approve/[category]`, params: Router.UnknownInputParams & { category: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/approve-main` | `/approve-main`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/hr-main` | `/hr-main`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/more-main` | `/more-main`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/resource-main` | `/resource-main`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(tabs)'}/approve/[category]` | `/approve/[category]`, params: Router.UnknownOutputParams & { category: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/approve-main${`?${string}` | `#${string}` | ''}` | `/approve-main${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/hr-main${`?${string}` | `#${string}` | ''}` | `/hr-main${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/more-main${`?${string}` | `#${string}` | ''}` | `/more-main${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/resource-main${`?${string}` | `#${string}` | ''}` | `/resource-main${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/approve-main` | `/approve-main`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/hr-main` | `/hr-main`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/more-main` | `/more-main`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/resource-main` | `/resource-main`; params?: Router.UnknownInputParams; } | `/+not-found` | `${'/(tabs)'}/approve/${Router.SingleRoutePart<T>}` | `/approve/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/approve/[category]` | `/approve/[category]`, params: Router.UnknownInputParams & { category: string | number; } };
    }
  }
}
